# Generated by Django 4.1.4 on 2022-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('duracao', models.IntegerField()),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
    ]
